Repository ReCoded-Org/capstone-iraq-rct-dilmun, pull requests merged in 2021-03, with the labels that each got.

#5 Add react-router-dom
  package.json
  yarn.lock
Labels: Build

#12 Add Tailwind
  craco.config.js
  package.json
  src/index.css
  tailwind.config.js
  yarn.lock
Labels: Build

#14 Adding i18next to support Multiple Langauges
  package.json
  src/i18n.js
  src/index.js
  src/locales/en.json
  src/locales/kr.json
  yarn.lock
Labels: Build

#10 Add redux
  package.json
  yarn.lock
Labels: Build

#35 80% done
  src/App.js
  src/assets/dilmun.png
  src/assets/kolara.png
  src/assets/profile_bg.png
  src/components/Navbar/Navbra.jsx
  src/components/navIInfo/ImageInfo.css
  src/components/navIInfo/ImageInfo.jsx
  src/containers/profile/Profile.css
  src/containers/profile/Profile.jsx
  src/index.js
Labels: Build

#42 profile has done
  package.json
  public/index.html
  src/App.js
  src/assets/1571937503463.jpeg
  src/assets/classy.jpg
  src/components/navIInfo/ImageInfo.css
  src/components/navIInfo/ImageInfo.jsx
  src/index.css
  yarn.lock
Labels: Build

#44 Feat: contact info card and font awsome icons
  src/App.js
  src/components/ContactInfoCard/ContactInfo.jsx
  src/components/ContactInfoCard/index.js
  src/containers/ProductDetails/ProductDetails.jsx
  src/fontawsome.js
Labels: Feat

#45 Draft: Adding Footer
  package.json
  src/App.js
  src/assets/Phone.png
  src/assets/email.png
  src/components/Footer/Footer.jsx
  src/components/Footer/index.js
  src/components/Navbar/NavBar.jsx
  src/containers/Home/Home.jsx
  src/fontawsome.js
  src/index.css
  src/locales/en.json
  src/locales/kr.json
  src/setupTests.js
  src/test/Footer/Footer.test.js
  src/test/Footer/__snapshots__/Footer.test.js.snap
  yarn.lock
Labels: Feat

#92 Feat & Test: carousal
  package.json
  src/App.css
  src/components/ItemsCarousal/Carousal.jsx
  src/components/ItemsCarousal/index.js
  src/containers/Home/Home.jsx
  src/test/Carousal/Carousal.test.js
  src/test/Carousal/__snapshots__/Carousal.test.js.snap
  src/test/ContactForm/__snapshots__/ContactForm.test.jsx.snap
  src/test/Footer/__snapshots__/Footer.test.js.snap
  tailwind.config.js
  yarn.lock
Labels: Feat, Test
