Repository ReCoded-Org/capstone-iraq-rct-dilmun, pull requests merged in 2021-04, with the labels that each got.

#121 Style: SearchForm
  src/components/SearchForm/SearchForm.jsx
Labels: Style

#128 Feat: Connect with Firebase Contact Form
  src/components/AddItemForm/AddItemForm.jsx
  src/components/ContactForm/ContactForm.jsx
  src/firebase.js
  src/locales/en.json
  src/locales/kr.json
Labels: Feat

#148 Feat: Build the functionality search page
  src/components/FilterOptions/FilterOptions.jsx
  src/components/Navbar/SecondaryNavbar.jsx
  src/components/SearchForm/SearchForm.jsx
  src/components/SearchPageCard/SearchPageCard.jsx
  src/containers/SearchResult/SearchResult.jsx
  src/router.js
  src/test/AddItemForm/__snapshots__/AddItemForm.test.jsx.snap
  src/test/ContactForm/__snapshots__/ContactForm.test.jsx.snap
  src/test/ContactInfoCard/__snapshots__/ContactInfoCard.test.js.snap
  src/test/FilterOptions/__snapshots__/FilterOptions.test.js.snap
  src/test/Footer/__snapshots__/Footer.test.js.snap
  src/test/SearchForm/__snapshots__/SearchForm.test.js.snap
  src/test/SearchPageCard/__snapshots__/SearchPageCard.test.js.snap
  src/test/SecondaryNavbar/__snapshots__/SecondaryNavbar.test.js.snap
Labels: Feat

#158 Fix: fix search result
  src/components/SearchForm/SearchForm.jsx
  src/components/SearchPageCard/SearchPageCard.jsx
Labels: Fix

#177 Feat: Build the UI for Checkbox
  src/components/CheckboxFilter/CheckboxFilter.jsx
  src/components/CheckboxFilter/index.js
  src/components/FilterOptions/FilterOptions.jsx
  src/containers/SearchResult/SearchResult.jsx
Labels: Feat

#181 Feat: Add the functionality to the checkbox
  src/components/CheckboxFilter/CheckboxFilter.jsx
  src/components/FilterOptions/FilterOptions.jsx
  src/containers/SearchResult/SearchResult.jsx
Labels: Feat

#190 Feat: add images to firebase
  src/components/AddItemForm/AddItemForm.jsx
  src/components/ProfileContentCard/ProfileContentCard.jsx
  src/firebase.js
  src/test/AddItemForm/__snapshots__/AddItemForm.test.jsx.snap
  src/test/ProfileCards/__snapshots__/Profile-cards.test.js.snap
Labels: Feat

#194 Bug: Fixed SecondaryNavbar Links
  src/components/CheckboxFilter/CheckboxFilter.jsx
  src/components/Navbar/SecondaryNavbar.jsx
  src/containers/SearchResult/SearchResult.jsx
  src/locales/en.json
  src/router.js
  src/test/SecondaryNavbar/__snapshots__/SecondaryNavbar.test.js.snap
Labels: Fix

#199 Style: Add item style
  src/App.js
  src/components/AddItemForm/AddItemForm.jsx
  src/components/ProfileContentCard/ProfileContentCard.jsx
  src/containers/AddItem/AddItem.jsx
  src/containers/Profile/Profile.jsx
  src/locales/en.json
  src/locales/kr.json
  src/test/AddItemForm/AddItemForm.test.jsx
  src/test/ProfileCards/Profile-cards.test.js
  src/test/ProfileCards/__snapshots__/Profile-cards.test.js.snap
Labels: Feat, Fix, Style

#198 Bug: Fix image uploading to the firebase
  src/components/AddItemForm/AddItemForm.jsx
  src/test/ProfileCards/Profile-cards.test.js
Labels: Fix

#211 Bug: Fix footer links and title
  src/components/Footer/Footer.jsx
  src/components/LandingPageCard/LandingPageCard.jsx
  src/components/SearchPageCard/SearchPageCard.jsx
  src/containers/SearchResult/SearchResult.jsx
Labels: Fix

#216 Style: Add ismail image
  src/assets/IsmailImg.jpg
  src/components/TeamMembers/TeamMembers.jsx
Labels: Style

#219 test fix
  package.json
  src/App.js
  src/components/AddItemForm/AddItemForm.jsx
  src/components/CheckboxFilter/CheckboxFilter.jsx
  src/components/ItemDetail/SlideShow.jsx
  src/test/AddItemForm/AddItemForm.test.jsx
  src/test/AddItemForm/__snapshots__/AddItemForm.test.jsx.snap
  src/test/ContactForm/__snapshots__/ContactForm.test.jsx.snap
  src/test/ContactInfoCard/ContactInfoCard.test.js
  src/test/ContactInfoCard/__snapshots__/ContactInfoCard.test.js.snap
  src/test/FilterOptions/__snapshots__/FilterOptions.test.js.snap
  src/test/Footer/__snapshots__/Footer.test.js.snap
  src/test/Header/__snapshots__/Header.test.js.snap
  src/test/ItemDetails/__snapshots__/ItemDetails.test.js.snap
  src/test/LandingPageCard/__snapshots__/LandingPageCard.test.js.snap
  src/test/ProfileCards/Profile-cards.test.js
  src/test/ProfileCards/__snapshots__/Profile-cards.test.js.snap
  src/test/SearchForm/__snapshots__/SearchForm.test.js.snap
  src/test/SearchPageCard/__snapshots__/SearchPageCard.test.js.snap
  src/test/SlisedShow/__snapshots__/SlideShow.test.js.snap
  src/test/TeamMembers/__snapshots__/AboutUs.test.jsx.snap
  src/test/TeamMembers/__snapshots__/TeamMembers.test.jsx.snap
  this.setState({
  yarn
  yarn.lock
Labels: Fix

#220 Doc: write the documentation
  README.md
Labels: Doc
